services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: young
      POSTGRES_PASSWORD: ly123456
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:                                                                                                                                                                               15,8          All
